name: Manual Food AI Digest (手動食品 AI 摘要)

on:
  workflow_dispatch: # 只允許手動觸發

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (檢出程式碼)
      uses: actions/checkout@v3

    - name: Set up Python (設定 Python 環境)
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies (安裝依賴套件)
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run research script (執行搜尋腳本)
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python main.py

    - name: Upload Digest Artifact (上傳摘要報告)
      uses: actions/upload-artifact@v4
      with:
        name: daily-digest
        path: food_ai_digest_*.md
        retention-days: 7
